language: node_js
node_js:
  - "7"
cache:
  directories:
    - server/node_modules
    - client/node_modules
services: mongodb
script: cd server && npm install && npm test && cd ../client && npm install && npm test
